architectury {
    platformSetupLoomIde()
    fabric()
}

dependencies {
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"

    implementation("me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config_version}") { transitive = false }
    implementation("com.terraformersmc:modmenu:${rootProject.fabric_mod_menu_version}") { transitive = false }

    common(project(':')) { transitive = false }
    shadowBundle project(path: ':', configuration: 'transformProductionFabric')
}

unifiedPublishing {
    project {
        displayName = "(Fabric) ${rootProject.mod_version} for MC ${rootProject.minecraft_version}"
        version = rootProject.version
        gameVersions = [rootProject.minecraft_version]
        gameLoaders = ['fabric']
        releaseType = 'release'

        mainPublication tasks.shadowJar

        relations {
            depends {
                curseforge = 'fabric-api'
                modrinth = 'fabric-api'
            }

            depends {
                curseforge = 'cloth-config'
                modrinth = 'cloth-config'
            }

            optional {
                curseforge = 'modmenu'
                modrinth = 'modmenu'
            }
        }

        curseforge {
            token = Objects.requireNonNullElse(System.getenv('CURSEFORGE_TOKEN'), "")
            id = rootProject.curseforge_project_id
        }

        modrinth {
            token = Objects.requireNonNullElse(System.getenv('MODRINTH_TOKEN'), "")
            id = rootProject.modrinth_project_id
        }
    }
}
