architectury {
    platformSetupLoomIde()
    fabric()
}

dependencies {
    implementation libs.fabricLoader
    implementation libs.fabricApi

    implementation(libs.clothConfigFabric) { transitive = false }
    implementation(libs.modMenu) { transitive = false }

    common(project(':')) { transitive = false }
    shadowBundle project(path: ':', configuration: 'transformProductionFabric')
}

unifiedPublishing {
    project {
        displayName = "(Fabric) ${rootProject.mod_version} for MC ${libs.versions.minecraft.get()}"
        version = rootProject.version
        gameVersions = rootProject.game_versions.split(',').toList()
        gameLoaders = ['fabric']
        releaseType = 'release'

        mainPublication tasks.shadowJar

        relations {
            depends {
                curseforge = 'fabric-api'
                modrinth = 'fabric-api'
            }

            depends {
                curseforge = 'cloth-config'
                modrinth = 'cloth-config'
            }

            optional {
                curseforge = 'modmenu'
                modrinth = 'modmenu'
            }
        }

        curseforge {
            token = Objects.requireNonNullElse(System.getenv('MOD_CURSEFORGE_TOKEN'), "")
            id = rootProject.curseforge_project_id
        }

        modrinth {
            token = Objects.requireNonNullElse(System.getenv('MOD_MODRINTH_TOKEN'), "")
            id = rootProject.modrinth_project_id
        }
    }
}
