architectury {
    platformSetupLoomIde()
    fabric()
}

dependencies {
    implementation libs.fabric.loader
    implementation libs.fabric.api

    implementation(libs.cloth.config.fabric) { transitive = false }
    implementation(libs.mod.menu) { transitive = false }

    common(project(':')) { transitive = false }
    shadowBundle project(path: ':', configuration: 'transformProductionFabric')
}
