plugins {
    id 'java'
    id 'maven-publish'
    alias(libs.plugins.architectury)
    alias(libs.plugins.architecturyLoom)
    alias(libs.plugins.shadow) apply false
    alias(libs.plugins.modPublish)
}

def minecraftVersion = libs.versions.minecraft.get()

base {
    archivesName = "$rootProject.archive_base_name-common"
}

architectury {
    common(project.enabled_platforms.split(','))
}

loom {
    accessWidenerPath = file('src/main/resources/diggusmaximus.accesswidener')

    runConfigs.configureEach {
        ideConfigGenerated = false
    }
}

dependencies {
    // In order to use the @Environment and @EnvironmentInterface annotations from fabric loader.
    implementation libs.fabricLoader

    implementation libs.clothConfig

    testImplementation platform(libs.junitBom)
    testImplementation libs.junitJupiter
    testRuntimeOnly libs.junitPlatformLauncher
}

sourceSets {
    main {
        resources {
            srcDir file('src/generated/resources')
            if (providers.gradleProperty('MOD_DEVELOPMENT').present) {
                srcDir file('src/test/resources')
            }
        }
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = project.base.archivesName.get()
            from components.java
        }
    }
}

allprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'
    apply plugin: 'architectury-plugin'
    apply plugin: 'dev.architectury.loom-no-remap'

    group = rootProject.maven_group
    version = "${rootProject.mod_version}+mc${minecraftVersion}"

    architectury {
        minecraft = minecraftVersion
    }

    loom {
        silentMojangMappingsLicense()

        interfaceInjection {
            enableDependencyInterfaceInjection = true
        }
    }

    repositories {
        maven {
            name = 'ParchmentMC'
            url = 'https://maven.parchmentmc.org'
        }

        maven {
            name = 'Mod Menu'
            url = 'https://maven.terraformersmc.com/releases'
        }

        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases/'
        }

        mavenCentral()
    }

    dependencies {
        minecraft libs.minecraft

        compileOnly libs.jetbrainsAnnotations

        compileOnly libs.lombok
        annotationProcessor libs.lombok

        testCompileOnly libs.lombok
        testAnnotationProcessor libs.lombok
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 25
    }

    java {
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_25
        targetCompatibility = JavaVersion.VERSION_25
    }

    jar {
        from('LICENSE') {
            rename { "${it}_${project.archive_base_name}" }
        }
    }

    processResources {
        var resourcesToReplace = [
                'pack.mcmeta',
                'META-INF/mods.toml',
                'META-INF/neoforge.mods.toml',
                'fabric.mod.json'
        ]

        var replaceTokens = [
                mod_id                             : rootProject.mod_id,
                mod_version                        : rootProject.mod_version,

                neoforge_minecraft_version_range   : rootProject.neoforge_minecraft_version_range,
                neoforge_loader_version_range      : rootProject.neoforge_loader_version_range,
                neoforge_version_range             : rootProject.neoforge_version_range,
                neoforge_cloth_config_version_range: rootProject.neoforge_cloth_config_version_range,

                fabric_minecraft_version_range     : rootProject.fabric_minecraft_version_range,
                fabric_loader_version_range        : rootProject.fabric_loader_version_range,
                fabric_api_version_range           : rootProject.fabric_api_version_range,
                fabric_cloth_config_version_range  : rootProject.fabric_cloth_config_version_range,
                fabric_mod_menu_version_range      : rootProject.fabric_mod_menu_version_range
        ]

        inputs.properties replaceTokens
        filteringCharset 'UTF-8'

        filesMatching(resourcesToReplace) {
            expand replaceTokens
        }
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }

    publishing {
        repositories {
            mavenLocal()

            maven {
                name = 'YuluoMaven'

                def releaseUrl = 'https://maven.yuluo.dev/repository/maven-releases/'
                def snapshotUrl = 'https://maven.yuluo.dev/repository/maven-snapshots/'
                url = providers.environmentVariable('MOD_RELEASE').isPresent() ? releaseUrl : snapshotUrl

                credentials {
                    username providers.environmentVariable('MOD_MAVEN_USER').get()
                    password providers.environmentVariable('MOD_MAVEN_PASS').get()
                }
            }
        }
    }
}

subprojects {
    apply plugin: 'com.gradleup.shadow'

    base {
        archivesName = "$rootProject.archive_base_name-$project.name"
    }

    loom {
        accessWidenerPath = project(':').loom.accessWidenerPath

        runs {
            client {
                client()
                runDir 'run/client'
            }

            server {
                server()
                runDir 'run/server'
            }

            configureEach {
                vmArg '-XX:+IgnoreUnrecognizedVMOptions'
                vmArg '-XX:+AllowEnhancedClassRedefinition'
                property 'file.encoding', 'UTF-8'
                property 'stdout.encoding', 'UTF-8'
                property 'stderr.encoding', 'UTF-8'
                property 'stdin.encoding', 'UTF-8'
            }
        }
    }

    configurations {
        common {
            canBeResolved = true
            canBeConsumed = false
        }

        compileClasspath.extendsFrom common
        runtimeClasspath.extendsFrom common
        developmentFabric.extendsFrom common
        developmentNeoForge.extendsFrom common

        shadowBundle {
            canBeResolved = true
            canBeConsumed = false
        }
    }

    dependencies {
    }

    jar {
        archiveClassifier = 'dev'
    }

    shadowJar {
        exclude 'architectury.common.json'
        configurations = [project.configurations.shadowBundle]
        archiveClassifier = ''
    }

    sourcesJar {
        def commonSources = rootProject.sourcesJar
        dependsOn commonSources
        from commonSources.archiveFile.map { zipTree(it) }
    }

    shadow {
        addShadowVariantIntoJavaComponent = false
    }

    publishing {
        publications {
            maven(MavenPublication) {
                artifactId = project.base.archivesName.get()
                from components.java
            }
        }
    }
}

publishMods {
    version = rootProject.version.toString()
    changelog = providers.environmentVariable('MOD_CHANGELOG').orElse('')
    type = STABLE
    dryRun = providers.environmentVariable('MOD_PUBLISH_DRY_RUN').isPresent()

    def curseforgeShared = curseforgeOptions {
        accessToken = providers.environmentVariable('MOD_CURSEFORGE_TOKEN')
        projectId = rootProject.curseforge_project_id
        minecraftVersions.addAll(rootProject.game_versions.split(','))
        client = true
        server = true
    }

    def modrinthShared = modrinthOptions {
        accessToken = providers.environmentVariable('MOD_MODRINTH_TOKEN')
        projectId = rootProject.modrinth_project_id
        minecraftVersions.addAll(rootProject.game_versions.split(','))
    }

    def fabricShared = publishOptions {
        file = project(':fabric').shadowJar.archiveFile
        displayName = "(Fabric) ${rootProject.mod_version} for MC ${minecraftVersion}"
        modLoaders.add('fabric')
    }

    def neoForgeShared = publishOptions {
        file = project(':neoforge').shadowJar.archiveFile
        displayName = "(NeoForge) ${rootProject.mod_version} for MC ${minecraftVersion}"
        modLoaders.add('neoforge')
    }

    curseforge('curseforgeFabric') {
        from(curseforgeShared, fabricShared)
        requires('fabric-api', 'cloth-config')
        optional('modmenu')
    }

    modrinth('modrinthFabric') {
        from(modrinthShared, fabricShared)
        requires('fabric-api', 'cloth-config')
        optional('modmenu')
    }

    curseforge('curseforgeNeoForge') {
        from(curseforgeShared, neoForgeShared)
        requires('cloth-config')
    }

    modrinth('modrinthNeoForge') {
        from(modrinthShared, neoForgeShared)
        requires('cloth-config')
    }
}
