org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
org.gradle.daemon=false

# Gradle plugins
architectury_plugin_version=3.4-SNAPSHOT
architectury_loom_version=1.11-SNAPSHOT
shadow_plugin_version=9.0.0+
unified_publishing_plugin_version=0.1.+

# Mod properties
mod_id=diggusmaximus
mod_version=1.7.8
maven_group=net.kyrptonaught
archive_base_name=diggus-maximus
enabled_platforms=fabric,neoforge

# Minecraft
minecraft_version=1.21.5
parchment_minecraft_version=1.21.5
parchment_version=2025.06.15

# Loaders version
neoforge_loader_version=4
neoforge_version=21.5.87
fabric_loader_version=0.16.14
fabric_api_version=0.128.1+1.21.5

# Dependencies version
fabric_mod_menu_version=14.0.0-rc.2
cloth_config_version=18.0.145
lombok_version=1.18.38

# Version range used in manifests
neoforge_minecraft_version_range=[1.21.5,)
neoforge_loader_version_range=[1,)
neoforge_version_range=[21.5,)
neoforge_cloth_config_version_range=[18,)

fabric_minecraft_version_range=>=1.21.5
fabric_loader_version_range=>=0.16
fabric_api_version_range=*
fabric_cloth_config_version_range=>=18

# Publishing
curseforge_project_id=977886
modrinth_project_id=tVeR4oKO
