org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
org.gradle.daemon=false

# Gradle plugins
architectury_plugin_version=3.4-SNAPSHOT
architectury_loom_version=1.11-SNAPSHOT
shadow_plugin_version=9.0.0+
unified_publishing_plugin_version=0.1.+

# Mod properties
mod_id=diggusmaximus
mod_version=1.7.6
maven_group=net.kyrptonaught
archive_base_name=diggus-maximus
enabled_platforms=fabric,neoforge

# Minecraft
minecraft_version=1.21.10
parchment_minecraft_version=1.21.9
parchment_version=2025.10.05

# Loaders version
neoforge_loader_version=4
neoforge_version=21.10.1-beta
fabric_loader_version=0.17.2
fabric_api_version=0.134.1+1.21.10

# Dependencies version
fabric_mod_menu_version=16.0.0-rc.1
cloth_config_version=20.0.148
lombok_version=1.18.42

# Version range used in manifests
neoforge_minecraft_version_range=[1.21.9,)
neoforge_loader_version_range=[1,)
neoforge_version_range=[21.9,)
neoforge_cloth_config_version_range=[20,)

fabric_minecraft_version_range=>=1.21.9
fabric_loader_version_range=>=0.16
fabric_api_version_range=*
fabric_cloth_config_version_range=>=20
fabric_mod_menu_version_range=*

# Publishing
curseforge_project_id=977886
modrinth_project_id=tVeR4oKO
