org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.cache=true
#org.gradle.configuration-cache=true

# Mod properties
mod_id=diggusmaximus
mod_version=1.8.0
maven_group=net.kyrptonaught
archive_base_name=diggus-maximus
enabled_platforms=fabric,neoforge

# Version range used in manifests
neoforge_minecraft_version_range=[26.2,26.3)
neoforge_loader_version_range=[1,)
neoforge_version_range=[26.2,26.3)
neoforge_cloth_config_version_range=[26.2,26.3)

fabric_minecraft_version_range=~26.2
fabric_loader_version_range=>=0.18
fabric_api_version_range=*
fabric_cloth_config_version_range=~26.2
fabric_mod_menu_version_range=*

# Publishing
game_versions=26.2
curseforge_project_id=977886
modrinth_project_id=tVeR4oKO
