architectury {
    platformSetupLoomIde()
    neoForge()
}

loom {
    runs {
        clientData {
            clientData()

            runDir 'run/data/client'

            programArgs '--all', '--mod', "${project.mod_id}"
            programArgs '--output', file('../src/generated/resources').absolutePath
            programArgs '--existing', file('../src/main/resources').absolutePath
        }

        serverData {
            serverData()

            runDir 'run/data/server'

            programArgs '--all', '--mod', "${project.mod_id}"
            programArgs '--output', file('../src/generated/resources').absolutePath
            programArgs '--existing', file('../src/main/resources').absolutePath
        }
    }
}

dependencies {
    neoForge "net.neoforged:neoforge:${rootProject.neoforge_version}"

    implementation("me.shedaniel.cloth:cloth-config-neoforge:${rootProject.cloth_config_version}") { transitive = false }

    common(project(':')) { transitive = false }
    shadowBundle project(path: ':', configuration: 'transformProductionNeoForge')
}

unifiedPublishing {
    project {
        displayName = "(NeoForge) ${rootProject.mod_version} for MC ${rootProject.minecraft_version}"
        version = rootProject.version
        gameVersions = rootProject.game_versions.split(',').toList()
        gameLoaders = ['neoforge']
        releaseType = 'release'

        mainPublication tasks.shadowJar

        relations {
            depends {
                curseforge = 'cloth-config'
                modrinth = 'cloth-config'
            }
        }

        curseforge {
            token = Objects.requireNonNullElse(System.getenv('CURSEFORGE_TOKEN'), "")
            id = rootProject.curseforge_project_id
        }

        modrinth {
            token = Objects.requireNonNullElse(System.getenv('MODRINTH_TOKEN'), "")
            id = rootProject.modrinth_project_id
        }
    }
}
