architectury {
    platformSetupLoomIde()
    neoForge()
}

loom {
    runs {
        data {
            clientData()

            runDir 'run/data'

            programArgs '--all', '--mod', "${project.mod_id}"
            programArgs '--output', file('../src/generated/resources').absolutePath
            programArgs '--existing', file('../src/main/resources').absolutePath
        }
    }
}

dependencies {
    neoForge libs.neoForge

    implementation(libs.clothConfigNeoForge) { transitive = false }

    common(project(':')) { transitive = false }
    shadowBundle project(path: ':', configuration: 'transformProductionNeoForge')
}
